ARG PYTHON_VERSION=3.12

# ==================================================
# Stage 0: Fetch the official python docker image
# ==================================================
FROM python:${PYTHON_VERSION} AS python-image

# =====================================================
# Step 1 (Build Stage): Dependencies installation layer
# =====================================================
FROM python-image AS python-build-stage

# =====================================================
# Do not use pip for poetry, poetry suggests to use pipx,
# But you have to manually install a complete system dependency
# This bloats the image and increases build time and overheads
# =====================================================
# RUN apt-get update && apt-get install --no-install-recommends -y \
#     build-essential \
#     curl \
#     && rm -rf /var/lib/apt/lists/*
# RUN pip install --no-cache-dir \
#     poetry==2.4.1 \
#     poetry-plugin-export

# =====================================================
# Best approach is to use officical poetry install using curl
# But then again you'll need pipx to inject export-plugin
# Because from 2.x export doesn't come pre-installed
# =====================================================
# RUN apt-get update && apt-get install --no-install-recommends -y \
#     curl \
#     pipx \
#     && rm -rf /var/lib/apt/lists/*
# RUN curl -sSL https://install.python-poetry.org | python3 - --version 2.4.1
# RUN pipx inject poetry poetry-plugin-export
# ENV PATH="/root/.local/bin:${PATH}"

# =====================================================
# We can install pipx and use it to install poetry and
# Inject the export plugin in poetry, and use that
# =====================================================
RUN apt-get update && apt-get install --no-install-recommends -y \
    pipx \
    && rm -rf /var/lib/apt/lists/*

RUN pipx install poetry==2.4.1 && \
    pipx inject poetry poetry-plugin-export
# Use pipx environment to get the actual path
# ENV PATH="$(pipx environment --value PIPX_BIN_DIR):${PATH}"
ENV PATH="/root/.local/bin:${PATH}"

COPY pyproject.toml poetry.lock /

RUN poetry export \
    -f requirements.txt \
    --output requirements.txt \
    --without-hashes

RUN pip wheel \
    --wheel-dir /usr/src/app/wheels \
    -r requirements.txt

# ===============================================================================
# Step 3 (Run Stage): Whatever is installed, ship in final image along with code
# ================================================================================
FROM python-image AS python-run-stage

WORKDIR /app

COPY --from=python-build-stage /usr/src/app/wheels /wheels

RUN pip install --no-cache-dir \
    --no-index \
    --find-links=/wheels \
    /wheels/*

# Copy Backend Code
COPY /config /app/config
COPY /project_apps /app/project_apps

# Copy executables
COPY /compose/local/django/entrypoint.sh /django-entrypoint.sh
COPY /compose/local/django/celerybeat/start.sh /beat-start.sh
COPY /compose/local/django/celeryworker/start.sh /worker-start.sh

# Give file permissions to executables
RUN chmod +x /django-entrypoint.sh
RUN chmod +x /beat-start.sh
RUN chmod +x /worker-start.sh

# TODO: Should we copy tests in development image
# COPY tests/ app/tests

# ENTRYPOINT ["/entrypoint.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
