# Generated by Django 5.2.14 on 2026-05-20 19:14

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import apps.payments_management.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_major', models.IntegerField(default=1)),
                ('version_minor', models.IntegerField(default=0)),
                ('version_patch', models.IntegerField(default=0)),
                ('version', models.CharField(blank=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_type', models.CharField(choices=[('default_invoice', 'Default Invoice Template')], default='default_invoice', max_length=124)),
                ('is_active', models.BooleanField(default=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoices on')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('defaulted', 'defaulted'), ('invalid', 'Invalid')], max_length=125)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=apps.payments_management.models.get_invoice_url)),
                ('context_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('payable_amount', models.FloatField(blank=True, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer_management.customer')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments_management.templates')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=124)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(blank=True, choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], max_length=124, null=True)),
                ('raw_payment_response', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('gateway_name', models.CharField(choices=[('pp', 'Pay Pal'), ('rz', 'Razorpay')], max_length=124, verbose_name='Paymeny Gateway')),
                ('gateway_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments_management.invoice')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customer_management.customer')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
