# Generated by Django 5.2.14 on 2026-06-09 22:43

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_major', models.IntegerField(default=1)),
                ('version_minor', models.IntegerField(default=0)),
                ('version_patch', models.IntegerField(default=0)),
                ('version', models.CharField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('invoice_created', 'Invoice Created'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded')], max_length=124)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('webhook', 'Webhook'), ('push_notification', 'Push Notification')], max_length=124)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], max_length=10, null=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('invoice_created', 'Invoice Created'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded')], max_length=124)),
                ('opted_email', models.BooleanField(default=False)),
                ('opted_sms', models.BooleanField(default=False)),
                ('opted_webhook', models.BooleanField(default=False)),
                ('opted_push_notification', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], max_length=124)),
                ('task_id', models.CharField(blank=True, max_length=124, null=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('webhook', 'Webhook'), ('push_notification', 'Push Notification')], max_length=124)),
                ('template_snapshot', models.TextField(blank=True, null=True)),
                ('context_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('errors', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='notifications.notificationtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
