# Generated by Django 5.2.14 on 2026-05-20 19:13

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=10, verbose_name='Mobile No')),
                ('email', models.EmailField(max_length=254)),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Mobile Verified')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('source', models.TextField(blank=True, null=True, verbose_name='Customer Source')),
                ('customer_type', models.CharField(choices=[('public', 'Public Customer'), ('private', 'Private Customer'), ('internal', 'Internal User')], max_length=124)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer External Reference')),
                ('details', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Customer Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=125, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_addresses', to='customer_management.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
