# Generated by Django 5.2.7 on 2026-04-25 16:03

from django.db import migrations
from project_apps.utils.tenant_utils import init_tenants, reverse_init_tenants

def do_initial_setup(apps, schema_editor):
    try:
        init_tenants()
    except Exception as e:
        raise e

def reverse_intial_setup(apps, schema_editor):
    try:
        reverse_init_tenants()
    except Exception as e:
        raise e

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [migrations.RunPython(do_initial_setup, reverse_intial_setup)]
