volumes:
  pg_data:
    name: bma_local_pg_data

secrets:
  global-env:
    file: ../.env

services:
  django: &Django
    build:
      context: ../backend
      dockerfile: dev.DockerFile
      secrets:
        - global-env
    container_name: bma_django
    restart: unless-stopped
    env_file:
      - ./.envs/django.env
      - ./.envs/postgres.env
    depends_on:
      postgres:
        condition: service_healthy
      bma_cache:
        condition: service_started
    volumes:
      - ../backend:/backend
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG=True
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONPATH=/
    ports:
      - "8000:8000"

  postgres:
    build:
      context: ./local/pg
      dockerfile: Dockerfile
      secrets:
        - global-env
    container_name: bma_postgres
    env_file:
      - ./.envs/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5

  frontend:
    build:
      context: ../frontend
      dockerfile: dev.Dockerfile
    container_name: bma_frontend
    restart: unless-stopped
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./.envs/vite.env

  bma_cache:
    image: valkey/valkey:8.1.5-alpine
    pull_policy: if_not_present
    container_name: bma_valkey_cache
    ports:
      - "6379:6379"

  bma_broker:
    image: valkey/valkey:8.1.5-alpine
    pull_policy: if_not_present
    container_name: bma_valkey_broker
    command: valkey-server --port 6378 --appendonly yes
    ports:
      - "6378:6378"
    healthcheck:
      test: ["CMD", "valkey-cli", "-p", "6378", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  bma_celeryworker:
    <<: *Django
    command: scripts/worker-start.sh
    container_name: bma_celeryworker
    ports:
      - "5555:5555"
    depends_on:
      django:
        condition: service_started
      bma_broker:
        condition: service_healthy

  # bma_celerybeat:
  #   <<: *Django
  #   command: backend/scripts/beat-start.sh
  #   container_name: bma_celerybeat
  #   depends_on:
  #     django:
  #       condition: service_started
  #     bma_broker:
  #       condition: service_healthy
