# Generated by Django 5.2.14 on 2026-06-30 15:48

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='interface_type',
            field=models.CharField(choices=[('ui_configuration', 'UI configuration'), ('notification_configuration', 'Notification configuration')], max_length=255),
        ),
        migrations.CreateModel(
            name='SeederExecutionLog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeder_name', models.CharField(max_length=255)),
                ('schema_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seeder_execution_log',
                'unique_together': {('seeder_name', 'schema_name')},
            },
        ),
    ]
