# Generated by Django 5.2.14 on 2026-05-20 19:13

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tenant Name')),
                ('in_production', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.organizationtenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_major', models.IntegerField(default=1)),
                ('version_minor', models.IntegerField(default=0)),
                ('version_patch', models.IntegerField(default=0)),
                ('version', models.CharField(blank=True, null=True)),
                ('country', models.CharField(choices=[('in', 'India'), ('us', 'United States')], default='in', max_length=125, verbose_name='Organization Country')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Organization Phone')),
                ('email', models.CharField(blank=True, null=True, verbose_name='Organization Email')),
                ('navbar_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('navbar_title', models.CharField(blank=True, max_length=100, null=True)),
                ('footer_icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Footer Icon(s) before Text')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='Text in Footer Section')),
                ('footer_extra_text', models.TextField(blank=True, null=True, verbose_name='Extra Text at end of footer')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tenants.organizationtenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
