# Generated by Django 5.2.7 on 2026-04-30 00:54

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfigurations',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_major', models.IntegerField(default=1)),
                ('version_minor', models.IntegerField(default=0)),
                ('version_patch', models.IntegerField(default=0)),
                ('version', models.CharField()),
                ('interface_type', models.CharField(choices=[('ui_configuration', 'UI configuration')])),
                ('details', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.organizationtenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
